-- MySQL Script generated by MySQL Workbench
-- Sat Sep  1 12:02:55 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empresa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `co_empresa` VARCHAR(5) NOT NULL,
  `emp_nombre` VARCHAR(65) NULL,
  `ruc` CHAR(10) NULL,
  `emp_sede(direccion)` VARCHAR(65) NULL,
  `emp_distrito` VARCHAR(45) NULL,
  `emp_provincia` VARCHAR(45) NOT NULL,
  `emp_departamento` VARCHAR(45) NULL,
  `emp_email` VARCHAR(65) NULL,
  `emp_telefono_contac` INT(9) NULL,
  `emp_ubigeo` CHAR(5) NULL,
  PRIMARY KEY (`co_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ubigeo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ubigeo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ubigeo` (
  `UBIGEO` CHAR(5) NOT NULL,
  `DEPARTAMENTO` VARCHAR(45) NULL,
  `PROVINCIA` VARCHAR(45) NULL,
  `DISTRITO` VARCHAR(45) NULL,
  `CONCA` VARCHAR(45) NULL,
  `ALTITUD` INT NULL,
  `SUPERFICIE` FLOAT NULL,
  `ESTADO_ALTITUD` VARCHAR(45) NULL,
  `LATITUD GOOGLE` VARCHAR(45) NULL,
  `LONGITUD GOOGLE` VARCHAR(45) NULL,
  `LATITUD` DOUBLE NULL,
  `LONGITUD` DOUBLE NULL,
  PRIMARY KEY (`UBIGEO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Punto_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Punto_venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Punto_venta` (
  `co_pto_venta` CHAR(7) NOT NULL,
  `pto_vta_nombre` VARCHAR(45) NULL,
  `pto_vta_departamento` VARCHAR(45) NULL,
  `pto_vta_provincia` VARCHAR(45) NULL,
  `pto_vta_distrito` VARCHAR(45) NULL,
  `pto_vta_direccion` VARCHAR(45) NULL,
  `pto_venta_ubigeo` CHAR(5) NULL,
  `Ubigeo_UBIGEO` CHAR(5) NOT NULL,
  PRIMARY KEY (`co_pto_venta`, `Ubigeo_UBIGEO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `cod_cli` CHAR(5) NOT NULL,
  `cli_tipo_doc_identi` VARCHAR(45) NULL,
  `cli_num_doc_identi` CHAR(8) NULL,
  `cli_nombre` VARCHAR(65) NULL,
  `cli_email` VARCHAR(45) NULL,
  `cli_telefono` CHAR(9) NULL,
  `genero` CHAR(2) NULL,
  `edad` INT NULL,
  PRIMARY KEY (`cod_cli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vendedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vendedor` (
  `cod_vend` CHAR(5) NOT NULL,
  `ven_nombre` VARCHAR(45) NULL,
  `ven_cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_vend`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `cod_producto` CHAR(7) NOT NULL,
  `pro_nombre` VARCHAR(45) NULL,
  `pro_categoria` VARCHAR(45) NULL,
  `pro_proveedor` VARCHAR(45) NULL,
  `pro_descripcion` VARCHAR(45) NULL,
  `pro_precio_uni` FLOAT NULL,
  PRIMARY KEY (`cod_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transaccion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transaccion` (
  `cod_tra` CHAR(5) NOT NULL,
  `tra_forma_campo` VARCHAR(10) NULL,
  `tra_medio_pago` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_tra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tiempo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tiempo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tiempo` (
  `cod_tie` CHAR(4) NOT NULL,
  `tie_mes` CHAR(2) NULL,
  `tie_trimestre` CHAR(1) NULL,
  `tie_año` CHAR(4) NULL,
  PRIMARY KEY (`cod_tie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TH_Boleta Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TH_Boleta Venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TH_Boleta Venta` (
  `Vendedor_cod_vend` CHAR(5) NULL,
  `Punto_venta_co_pto_venta` CHAR(7) NULL,
  `Tiempo_cod_tie` CHAR(4) NULL,
  `Transaccion_cod_tra` CHAR(5) NULL,
  `Cliente_cod_cli` CHAR(5) NULL,
  `Producto_cod_producto` CHAR(7) NULL,
  `Empresa_co_empresa` VARCHAR(5) NULL,
  `TH_cod` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TH_cod`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
